# --- RECOMMENDED docker-compose.yml ---
services:
  ptb:
    build: .
    env_file: .env
    volumes:
      # This mounts your local PTB folder into the container's /app directory
      - ./PTB:/app
